version: '3.8'

services:
  db:
    build: ./database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
